<!-- 锚点 -->
<template>
  <div id="app">
    <button @click="returnToA">跳转到A</button>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>a</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>b</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div id="header">cmmmmmmm</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
    <div>c</div>
  </div>
</template>

<script>
export default {
  data: {},
  methods: {
    returnToA() {
      console.log("点击成功");
      document.querySelector("#header").scrollIntoView();
    },
  },
};
</script>

<style lang="scss" scoped>
button {
  font-size: 16px;
}
</style>
